# 文件: configs/config.example.yaml

server:
  port: ":8080"

redis:
  addr: "127.0.0.1:6379"
  password: ""
  db: 0

kafka:
  brokers:
    - "127.0.0.1:9092"

rabbitmq:
  url: "amqp://user:password@localhost:5672/"

logger:
  dir: "./logs"
  max_size_mb: 100
  max_keep_days: 7
