# 文件: configs/config.yaml

# 服务端口
server:
  port: ":8080"

# 数据库
mysql:
  dsn: "go_pro:2005@tcp(127.0.0.1:3306)/go_flash_job?charset=utf8mb4&parseTime=True&loc=Local"

# Redis
redis:
  addr: "127.0.0.1:6379"
  password: ""
  db: 0

# Kafka
kafka:
  brokers:
    - "127.0.0.1:9092"

# RabbitMQ
rabbitmq:
  url: "amqp://admin:admin@localhost:5672/"
