# 文件: configs/config.yaml

# 服务端口
server:
  port: ":8080"

# Redis
redis:
  addr: "127.0.0.1:6379"
  password: ""
  db: 0

# Kafka
kafka:
  brokers:
    - "127.0.0.1:9092"

# RabbitMQ
rabbitmq:
  url: "amqp://admin:admin@localhost:5672/"

# 日志文件配置
logger:
  dir: "./logs"
  max_size_mb: 100        # 单文件最大 100MB
  max_keep_days: 7        # 保留 7 天
